### ISSUE TITLE
Handeling navigation through the application

### ISSUE THREAD

**Issue by arajanrai** [Bancard/bancard-checkout-js#11]
Hey, is there any way to handle the navigation through the application using this JS file and not use the default navigation which this js file is using like `window.location.replace`.

We are using ionic 5 app and it starts showing white screen because of the internal navigation happening because of bancard checkout js.

**Comment by olrtg** [comment]
Hey @arajanrai!
AFAIK, there's no way to disable that behavior. Last year we were using Ionic 4 for a client's project and what we did was let the back-end handle the card registration. In the app we just added an InAppBrowser and passed the PROCESS_ID as a URL param.

Hope this help you in some way.
Greetings from Paraguay!
